WITH TEST_STG_CTE AS
(
    SELECT 
        ID AS ID_NO,
        FNAME AS FIRST_NAME,
        LNAME AS LAST_NAME,
        ADDRESS AS BILLING_ADDRESS,
        CITY AS BILLING_CITY,
        CONCAT(FNAME, ' ', LNAME) AS CUSTOMER_FULL_NAME
    FROM TEST_DB.PUBLIC.CUSTOMER_INFO
)

SELECT * from TEST_STG_CTE 